---
galaxy_info:
  role_name: splunk_enterprise
  author: IaaS
  description: Install Splunk Enterprise 10 as a single Linux instance
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm

dependencies: []
